language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  skip_cleanup: true
  email: dengshuaihui@gmail.com
  on:
    tags: true
  api_key:
    secure: dHs0HC9aOtDCwdfbiV5PD2T3hN0g10/looEs8fO7GnRlwH8wGsy9NaVrz8pxZeG9eqVYV/oMDjoo+Cmy1H+bpyPRjS4EbzDSBSmGXkj38j3nQ60HH2ViwX0XMROP4hJFqTdbKy5ALDwJIhq+vGPNYZSiUtc1fOTWp/a1dloprmK8GuxchEA2B4AFGureswtP1EO8cPYdI9UNDh7Z0L9O6ewLyx53mYaRMrNKV4qAi8UxPUBsWj4EFHQ8PCBKY2hAa2UnLEcXKZ5o43v7YymMtYEgfpO9I8eyxsYnDsk0Fur0+NDwW0UlCWJKnwPEFEI/TgL7daKjkG3MP9QOWy7fED8sDzGxjgElxCOtkH9m/g9uEn8H/hJ+ryYpDcKcepDsqARW0a5ZbjB4iPqTFaQpoNWZZvqeOi6IvQcXbtg229buQ6zQdKW9rmiVns1cAP3U2utIJ4Ac517LkFr2AvXO+bxkRvyPcJYwjHhQlsf8GV4WmXN7pCEFepeAUqGjJ3UmX66etkG4phl2+6RPf93pRAD1cpSfcROEVQvh8tLKDvKRL47F0u+l6mosZQuF7dIhXqzzj/YjtwTB874N29Xx74e4YXsHJeixdPgC9oxvBTOiEAtGY1RHnWgqNVBY7eZXFPzfOf6iXtl3kmqsL1rm7S4ZxG9bxd5purUQ3VpR1Wg=
  api_token:
    secure: iw2CVP0i5wUWLw84hjs5yRZJSn20e6kgADcZFToRiUEdpBciDT1E/8vnvKGBOvYSjNebWuE4vmER1pYlhWRHWVuyp1B0rPrn/g6wBJ8x2G3w+P5kuvBGjPAvPy5UoQY/gXkhh6zDk/cCJjuohs1Musc4wRi/gB/eJNCYFcNuiFGvT3XWaSezc/eY6zmi+oNIfahdmGm4u0mr3iXqlSg2b4wiwXGiTWWdpmbYG2tD1PcpGefvDuyMJEos8laMYPtHWswRqOnPaJNQw/5YA8AaZurATjNAcVu65a6AVF8aNKlU/FbuqCDhtPnS05ZYjK/k/uRwZI06vQGf8DFRXttMqAssF9+xiRJODeythsrm+DmwAkYnC76uP7Rg7UnMpec1nXTWTKMYGo/erXdx6Wx9a7gJUm5lClAQqvARxYph2d7XCPJ4WbJEDZGajMwXFCboQEFpYZJmimR0x/WtZ2+WXdfJeQw24vAsUYxodLNGzh+QZd8a5CpBaGC4HQ9w1vb+XOIAjrAHB9PH20DHUti6KYzSHEHMipRlyfT8k+vECREkF26Tj2Ly3oQSolwbvxGMNNcrmWaGrhfjGfvnXpP0C+UpKDa7ovpCjAdjhusi6+Yx2bXoo6JY5n4142dB4MUyflSoeDUoGlhDf2pWwtHK8iH7XHHIFgOH8oRZPPOHO2E=
