language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  provider: npm
  email: dengshuaihui@gmail.com
  on:
    tags: true
  api_token:
    secure: qE2xjz1TJE0sXmuzeqJl+WHK/fQiFkkGTaXHqMOq8mbzUGriBC4uB4XR6qblvnfS6xoeiMRICPhqPGHSJzkz1gbrKhaEjZN5X5RXXRD6EtEsLlwck+iYQsKQtaol/PBEgv/Pm3DMJBd/rUsW9M49s2CbBzwpQiVVB32jv2Wqfbkc3cxQq9vXuIFdnK1ADMOpRlqiad/eAVVFHOpqqWAhZP79lzWECiKV78w5qmB+Vso2vBm0/bk/wvIEY8u67Ka4zwyikdvAILacO0AIAOxruDtvYXRFMarMRzetAuojpRyV82RMQs4v++/feGnnZHKHsg+Aer5pfZpM82A4CyG3H6reGq0bTyYfBnhKcehLfGM/BC1vMLsIw3Jr4j+RZkV1UbE7S8IqtBpKTQhrNg1LtINUlViKiqMXBEutAe8TZYUaaRX8iZRLrAu6JON7ai5z3zvdxDQw9uUNjHNfjl8k9mYXDszs0dglDV7H7la93rkdUL4DGu0+5aovTFBwK3sUdj18fwDKtSlTzFaVy8AK4OrCxDwyZAczCfkVBPsEpo1JY4Y/54/hbAcG5KYAgwuxz4ZQG9QoVIBKxHe3q3L0YRMVTq17euKYWtQ9CloIscgt7fl8DqkhdG1Ils/wfWhaDSTc4HbDtlNAy84Ema4o6P3k9LQUp50pSiP567sxayI=
